#pragma once

#include <Process/Drop/ProcessDropHandler.hpp>

#include <Library/LibraryInterface.hpp>
#include <Library/LibrarySettings.hpp>
#include <Library/ProcessesItemModel.hpp>

#include <QFileInfo>

#include <Airwindows/ProcessModel.hpp>

#include <AirwinRegistry.h>

namespace Airwindows
{
inline void initializeRegistry()
{
  static bool initialized = false;
  if(!initialized)
  {
    // The registry should be populated by the autogenerated code
    AirwinRegistry::completeRegistry();
    initialized = true;
  }
}

class LibraryHandler final
    : public QObject
    , public Library::LibraryInterface
{
  SCORE_CONCRETE("5aff3580-21d3-4069-bd08-823371245a5b")
public:
  void setup(Library::ProcessesItemModel& model, const score::GUIApplicationContext& ctx)
      override
  {
    const auto& key = Metadata<ConcreteKey_k, Airwindows::ProcessModel>::get();

    // Initialize the airwindows registry
    initializeRegistry();

    // Stage the whole registry; the model owns tree mutation and signals.
    ossia::hash_map<std::string, std::size_t> categories;
    std::vector<Library::StagedNode> staged;
    staged.reserve(AirwinRegistry::categories.size());
    for(const auto& cat : AirwinRegistry::categories)
    {
      categories[cat] = staged.size();
      staged.push_back(
          Library::StagedNode{{{{}, QString::fromStdString(cat), {}}, {}}, {}});
    }
    for(const auto& plugin : AirwinRegistry::registry)
    {
      Library::StagedNode p{
          {{key, QString::fromStdString(plugin.name),
            QString::fromStdString(plugin.name)},
           {}},
          {}};
      if(auto it = categories.find(plugin.category); it != categories.end())
        staged[it->second].children.push_back(std::move(p));
      else
        staged.push_back(std::move(p));
    }
    std::sort(staged.begin(), staged.end(), [](const auto& lhs, const auto& rhs) {
      return QString::compare(
                 lhs.data.prettyName, rhs.data.prettyName, Qt::CaseInsensitive)
             < 0;
    });

    model.clearAnchorKey(key);
    model.replaceChildren(key, std::move(staged));
  }
};

}
