#pragma once

namespace Airwindows
{

/**
 * @brief Build AirwinRegistry's name and category indices. Idempotent, thread-safe.
 *
 * The registry itself is filled by the autogenerated static initializers; this adds
 * the lookup tables on top, and pins a fallback sample rate: a few effects call
 * getSampleRate() from their constructor, which asserts on the shipped default of
 * zero. Every instance we make gets its real rate set straight after, but the
 * constructor runs before we get the chance.
 */
void initializeRegistry();

}
